config/routes.rb
Rails.application.routes.draw do
  root to: 'subs#index'

  resources :users, except: [:index, :show, :destroy]
  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, except: [:index]
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :sub_id, :author_id, presence: true

  belongs_to :author,
    class_name: :User
  belongs_to :sub
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true
  validates :title, uniqueness: true

  has_many :posts, dependent: :destroy
  belongs_to :moderator,
    class_name: :User
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  after_initialize :ensure_session_token

  has_many :subs
  has_many :posts

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.is_password?(password)
    nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    set_password_digest
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def set_password_digest
    self.password_digest = BCrypt::Password.create(password)
    self.save
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def login_user!(user)
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_author_edit, only: [:edit, :update]
  before_action :require_delete, only: [:destroy]

  def new
    @post = Post.new
    @sub_id = params[:sub_id]
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.sub_id = params[:sub_id]
    @post.author_id = current_user.id
    if @post.save
      flash[:notice] = "Successfully created a post!"
      redirect_to sub_url(@post.sub_id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])

    if @post
      render :show
    else
      redirect_to root_url
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    render :edit
  end

  def update
    @post = Post.find_by(id: params[:id])

    if @post.update_attributes(post_params)
      redirect_to sub_post_url(@post.sub_id, @post.id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post
      flash[:notice] = "Post deleted"
      @post.destroy
    else
      flash[:notice] = "Post does not exist"
    end

    redirect_to sub_url(@post.sub_id)
  end

  private

  def require_author_edit
    @post = Post.find_by(id: params[:id])
    unless current_user.id == @post.author_id
      flash.now[:errors] = "You must be the author to edit"
      render :show
    end
  end

  def require_delete
    @post = Post.find_by(id: params[:id])
    @sub = Sub.find_by(id: @post.sub_id)
    unless current_user.id == @sub.moderator_id ||
      current_user.id == @post.author_id
      flash.now[:errors] = "You must be the author or moderator to delete"
      render :show
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id, :author_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])

    if @user
      login_user!(@user)
      flash[:notice] = "You have logged in!"
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    logout!
    render :new
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_moderator, only: [:edit, :update, :destroy]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      flash[:notice] = "Successfully created a sub!"
      redirect_to root_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find_by(id: params[:id])

    if @sub
      render :show
    else
      redirect_to root_url
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(id: params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])

    if @sub
      flash[:notice] = "Sub deleted"
      @sub.destroy
    else
      flash[:notice] = "Sub does not exist"
    end

    redirect_to root_url
  end

  private

  def require_moderator
    @sub = Sub.find_by(id: params[:id])
    unless current_user.id == @sub.moderator_id
      flash.now[:errors] = "You must be the moderator"
      render :show
    end
  end


  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Sign up successful!"
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul>
<% if current_user %>
  <li><%= current_user.username %></li>
  <li><%= link_to "Create a sub", new_sub_url, method: :get %></li>
  <li><%= link_to "All subs", root_url, method: :get %></li>
  <li><%= link_to "Logout", session_url, method: :delete %></li>
<% else %>
  <li><%= link_to "Sign in", new_session_url, method: :get %></li>
  <li><%= link_to "Sign up", new_user_url, method: :get %></li>
<% end %>
</ul>

<%= flash.now[:notice] if flash %>
<%= flash.now[:errors] if flash %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% action = (sub_post.persisted? ? sub_post_url(sub_post.sub_id, sub_post.id) : sub_posts_url) %>
<% method = (sub_post.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="title">Title:</label>
  <input type="text" name="post[title]" value="<%= sub_post.title %>">
  <br>

  <label for="url">URL:</label>
  <input type="text" name="post[url]" value="<%= sub_post.url %>">
  <br>

  <label for="content">Content:</label>
  <textarea name="post[content]" rows="8" cols="80"><%= sub_post.content %>
  </textarea>
  <br>

  <input type="submit" name="" value="Submit">
</form>

app/views/posts/edit.html.erb
<h1>Edit Post!</h1>

<%= render "form", sub_post: @post %>

app/views/posts/new.html.erb
<h1>New Post!</h1>

<%= render "form", sub_post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<h3>Author: <%= @post.author.username %></h3>

<%= link_to @post.url %>

<p><%= @post.content %></p>

<% if current_user.id == @post.author_id %>
  <%= link_to "Edit", edit_sub_post_url(@post.sub_id, @post.id), method: :get %>
  <%= link_to "Delete", sub_post_url(@post.sub_id, @post.id), method: :delete %>
<% elsif current_user.id == @post.sub.moderator_id %>
  <%= link_to "Delete", sub_post_url(@post.sub_id, @post.id), method: :delete %>
<% end %>

app/views/subs/_form.html.erb
<% action = (sub.persisted? ? sub_url(sub) : subs_url) %>
<% method = (sub.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="title">Title:</label>
  <input type="text" name="sub[title]" value="<%= sub.title %>">
  <br>

  <label for="description">Description:</label>
  <textarea name="sub[description]" rows="8" cols="80"><%= sub.description %>
  </textarea>
  <br>

  <input type="submit" name="" value="Submit">
</form>

app/views/subs/edit.html.erb
<h1>Edit Sub!</h1>

<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1>Subs</h1>

<ul>
  <% @subs.each do |sub| %>
    <li><%= link_to "#{sub.title}", sub_url(sub), method: :get %></li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h1>New Sub!</h1>

<form class="" action="/subs" method="post">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="title">Title</label>
  <input type="text" name="sub[title]" value="">

  <br>

  <label for="description">Description</label>
  <textarea name="sub[description]" rows="8" cols="80"></textarea>

  <br>

  <input type="hidden" name="sub[moderator_id]" value="<%= current_user.id %>">

  <input type="submit" name="" value="Submit">
</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<h3>Moderator: <%= @sub.moderator.username %></h3>

<p><%= @sub.description %></p>

<% if current_user %>
  <%= link_to "Add Post", new_sub_post_url(@sub.id), method: :get %>
<% end %>

<% if current_user.id == @sub.moderator_id %>
  <%= link_to "Edit", edit_sub_url, method: :get %>
  <%= link_to "Delete", sub_url(@sub), method: :delete %>
<% end %>

<h2>Posts</h2>
<ul>
  <% @sub.posts.each do |post| %>
    <li><%= link_to post.title, sub_post_url(post.sub_id, post.id) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New User!</h1>

<form class="" action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="username">Username</label>
  <input type="text" name="user[username]" value="">
  <label for="password">Password</label>
  <input type="text" name="user[password]" value="">

  <input type="submit" name="" value="Submit">
</form>